language: python
python:
 - 3.6
before_install:
  - export GOPATH=$HOME/golang
  - export PATH=$PATH:$GOPATH/bin
install:
 - pip install tox-travis
 - eval "$(gimme 1.7)"
 - go get github.com/ValeLint/vale
script:
 - tox
env:
  - TEST="lint"
  - TEST="docs"
