name: Australia

shortcode: australia # prague australia?
templatecode: au # HACK
year: 2019
city: Sydney
local_area: Australia
area: Australia
area_adj: Australian
tz: AEST
email: australia@writethedocs.org
color: coral

photos:
  default: _static/2019/assets/headers/WTDHeader.png

tickets:
  corporate:
    price: $250
  independent:
    price: $150
  student:
    price: $75

sponsorship:
  first_draft:
    price: $500
  second_draft:
    price: $1000
  publisher:
    price: $2000
  patron:
    price: $4000
  keystone:
    price: $7500

date: # how do we handle these? human readable would be nice.
  main: "**November 14-15, 2019, in Sydney, Australia**"
  short: Nov 14-15, 2019
  tickets_live: "May 2019"
  month: November
  sat:
  day_one:
    event: Talks/Doc sprints
    date: Nov 14
    summary: The first conference day, including talks, doc sprints, and unconference time.
    icon: conference
  day_two:
    event: Talks
    date: Nov 15
    summary: Another day of talks, unconference and discussion time.
    icon: conversation

about:
  summary: "TBD"
  location: "TBD"
  attendees: 100
  mainroom:
    Performance Space
  unconfroom:
    Community Room

cfp:
  url: https://goo.gl/forms/ONK3MoLwtNQ3LcXv1
  ends: Friday, July 27th
  notification: Wednesday, Aug 15th

flaglanding: True
flagspeakersannounced: False
flagcfp: False
flaghassponsors: False
flaghasschedule: False

flagticketsonsale: False
flaghashike: False
flaghasboat: False
flagvideos: False
flaglivestreaming: False
