name: Prague

shortcode: prague # prague australia?
templatecode: eu # HACK
year: 2018
city: Prague
area: European
tz: CEST
email: prague@writethedocs.org

tickets:
  community:
    price: €500
  corporate:
    price: €250
  independent:
    price: €150
  student:
    price: €75

sponsorship:
  first_draft:
    price: €500
  second_draft:
    price: €1000
  publisher:
    price: €3000
  patron:
    price: €6000
  keystone:
    price: €12000
  job_fair:
    price: €800
    half: €400
  lanyard:
    price: TBD
  writing_day:
    price: TBD

date: # how do we handle these? human readable would be nice.
  main: "**September 9-11, 2018, in Prague, Czechia**"
  tickets_live: "March 2018"
  month: September
  day_one:
    date: 8
    dotw: Saturday
  day_two:
    date: 9
    dotw: Sunday
  day_three:
    date: 10
    dotw: Monday
  day_four:
    date: 11
    dotw: Tuesday

about:
  summary:
    "The main presentation track takes place from **September 9-11 (Monday and Tuesday) from 10:00 to 18:00**.
    During the main event we also run an :doc:`/conf/prague/2018/unconference`.

    You can find out more information about the venue and its accessibility on our :doc:`/conf/prague/2018/venue` page."
  venue:
    "Auto Klub, Opletalova 29, Prague"
  attendees: 300
  mainroom:
    Main Ballroom
  unconfroom:
    Unconference Room, downstairs

cfp:
  url: FIXME
  ends: Sunday, May 13th
  notification: Sunday, June 10th

job_fair:
  location: Unconference Room, downstairs

flagspeakersannounced: False
flagcfp: False
flagticketsonsale: False
flaghashike: False
flaghasboat: True
